"""Initial schema

Revision ID: 5248cd980261
Revises: 
Create Date: 2026-08-26 09:54:54.105971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5248cd980261'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_rpm', sa.Integer(), nullable=True),
    sa.Column('tyre_radius', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_index(op.f('ix_cars_name'), 'cars', ['name'], unique=True)
    op.create_table('tracks',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('layout_variant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_index(op.f('ix_tracks_layout_variant'), 'tracks', ['layout_variant'], unique=False)
    op.create_index(op.f('ix_tracks_name'), 'tracks', ['name'], unique=True)
    op.create_table('corners',
    sa.Column('corner_id', sa.Integer(), nullable=False),
    sa.Column('corner_number', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.PrimaryKeyConstraint('corner_id')
    )
    op.create_index(op.f('ix_corners_name'), 'corners', ['name'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_session_type'), 'sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_sessions_started_at'), 'sessions', ['started_at'], unique=False)
    op.create_table('laps',
    sa.Column('lap_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('lap_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('lap_id')
    )
    op.create_table('corner_performances',
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('entry_speed_kmh', sa.Float(), nullable=True),
    sa.Column('time_in_corner_ms', sa.Integer(), nullable=True),
    sa.Column('lap_id', sa.Integer(), nullable=True),
    sa.Column('corner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corner_id'], ['corners.corner_id'], ),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.lap_id'], ),
    sa.PrimaryKeyConstraint('performance_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('lap_id', sa.Integer(), nullable=True),
    sa.Column('corner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corner_id'], ['corners.corner_id'], ),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.lap_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('telemetry',
    sa.Column('telemetry_id', sa.Integer(), nullable=False),
    sa.Column('packet_id', sa.Integer(), nullable=True),
    sa.Column('normalised_pos', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('lap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.lap_id'], ),
    sa.PrimaryKeyConstraint('telemetry_id')
    )
    op.create_table('video_clips',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('clip_id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_clips')
    op.drop_table('telemetry')
    op.drop_table('events')
    op.drop_table('corner_performances')
    op.drop_table('laps')
    op.drop_index(op.f('ix_sessions_started_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_type'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_corners_name'), table_name='corners')
    op.drop_table('corners')
    op.drop_index(op.f('ix_tracks_name'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_layout_variant'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_cars_name'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
